networks:
  default:
    name: druid-container_default

volumes:
  mysql:

services:
  traefik:
    image: traefik:v3.3.2
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.mysql.address=:3306"
    ports:
      - "${TRAEFIK_PORT:-80}:80"
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/dev/traefik/configuration:/configuration"
      - "./docker/dev/traefik/certs-with-ca/:/certs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_HOST:-traefik.druid-container.localhost}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
    networks:
      default:
        aliases:
          - ${APP_HOST:-druid-container.localhost}

  php-fpm:
    build:
      context: ./docker/dev/php-fpm
      dockerfile: Dockerfile
      args:
        WWWUSER: "${WWWUSER:-1000}"
        WWWGROUP: "${WWWGROUP:-1000}"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /application
    volumes:
      - ".:/application"
      - "./docker/dev/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
    environment:
      FORCE_HTTPS: "true"

  node:
    platform: linux/amd64
    build: ./docker/dev/node
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ".:/application"
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node-http.entrypoints=web"
      - "traefik.http.routers.node-http.rule=Host(`${VITE_SERVER_HOST:-vite-server.druid-container.localhost}`)"
      - "traefik.http.services.node.loadbalancer.server.port=5173"

  web:
    image: nginx:1.27.3-alpine3.20
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ".:/application"
      - "./docker/dev/web/templates:/etc/nginx/templates:rw,cached"
    environment:
      FPM_HOST: php-fpm:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${APP_HOST:-druid-container.localhost}`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - "mysql:/var/lib/mysql"
      - "./docker/dev/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 3
      timeout: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
      - "traefik.tcp.services.mysql.loadbalancer.server.port=3306"
